=== Dandddyy/ROlab7/football.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="palyerType">
        <xs:sequence>
            <xs:element name="Id" type="xs:integer"/>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Country" type="xs:string"/>
            <xs:element name="Position" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="teamType">
        <xs:sequence>
            <xs:element name="Id" type="xs:integer"/>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Country" type="xs:string"/>
            <xs:element name="Player" type="palyerType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="footballType">
        <xs:sequence>
            <xs:element name="Team" type="teamType" maxOccurs="unbounded">
                <xs:unique name="uniqueid">
                    <xs:selector xpath="Player"/>
                    <xs:field xpath="Id"/>
                </xs:unique>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="Football" type="footballType">
        <xs:unique name="uniqueId">
            <xs:selector xpath="Team"/>
            <xs:field xpath="Id"/>
        </xs:unique>
    </xs:element>

</xs:schema>

=== Dandddyy/ROlab7/football.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><Football xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="football.xsd"><Team><Id>1</Id><Name>Chelsea</Name><Country>England</Country><Player><Id>1</Id><Name>Mudryk</Name><Country>Ukraine</Country><Position>LW</Position></Player><Player><Id>2</Id><Name>Silva</Name><Country>Brazil</Country><Position>CB</Position></Player><Player><Id>3</Id><Name>Sterling</Name><Country>England</Country><Position>RW</Position></Player></Team><Team><Id>2</Id><Name>Barcelona</Name><Country>Spain</Country><Player><Id>1</Id><Name>Bellingham</Name><Country>England</Country><Position>CM</Position></Player></Team></Football>
